# Project Overview {.unnumbered}



## Purpose {.unnumbered}
The purpose of the [name] Watershed Connectivity Restoration Plan (WCRP) is to improve understanding of habitat connectivity for [focal species] in the [X Watershed or X, Y, and Z watersheds] and inform efforts to close knowledge gaps and prioritize restoration. 
Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. 
This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. 
As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 


## Current Connectivity Status {.unnumbered}
In the [X Watershed or X, Y, and Z watersheds], [X] km of [focal species] habitat are currently connected to the ocean and [X] km are disconnected from it. This means that [X]% of the [X] km of total habitat is connected. 

 

In the [X Watershed or X, Y, and Z watersheds], [X] structures potentially disconnect [focal species] habitat. Of these, [X] are identified as barriers in need of rehabilitation (priority barriers), [X] are identified as barriers that do not warrant rehabilitation (non-actionable), and [X] require further field assessment. 

## Habitat Accumulation Curve {.unnumbered}
```{r echo = FALSE}
#| results: hide
#| message: false
#| warning: false

source("content/Rscripts/create_HAC.R")
plot_cumulative_avg_gain("content/data/combined_tracking_crossings_LNIC.csv")

```
![Figure 1: Habitat Accumulation Curve (HAC) showing structures in the Lower Nicola watershed as of x date. Structures are ranked based on how much (km) habitat is upstream to the next structure or set of structures and that would be reconnected if the structure(s) became passable. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of data-deficient structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown; however, rehabilitated barriers are shown to demonstrate the connectivity gains achieved through implementation of this plan. ](content/images/hac-lnic-test.png){fig-align="left"}

## Map {.unnumbered} 

![Map of [focal species] habitat and structures that are confirmed or potential barriers to fish passage in the [X Watershed or X, Y, and Z watersheds] as of [dd month year]. Structure data were obtained from the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that [focal species] could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible areas that may be used by [focal species for key habitat function(s)]. Available local knowledge and data were incorporated and overruled habitat model results. Thick light-blue lines represent habitat that is currently connected, whereas thick red lines represent habitat considered to be disconnected because it is upstream of barriers or unassessed structures. Barriers that were rehabilitated through implementation of this plan are shown, but other excluded structures (e.g., those found to be passable) are not.](content/images/hac-map-lnic.png)

## Progress Summary {.unnumbered}
This WCRP was initiated in [year]. Since then, the passability of [X] structures has been assessed, and further habitat assessments were completed at [X] of these. Fish passage has been rehabilitated at [X] barriers, resulting in improved or restored access to [X] km of habitat. [Add summary of any other activities that have been completed]. 

## Recommended Citation {.unnumbered}
