# Progress Reporting {-}

## Progress Summary {-}

This WCRP was initiated in 2025 in partnership between the Chéticamp River Salmon Association (CRSA) and the Canadian Wildlife Federation (CWF). In the development phase of this project, a tributary-by-tributary mapping exercise was conducted to gather local knowledge, and fish passage was assessed in the field at 36 sites, and this data were incorporated into the model.

## Rehabilitated Barriers {-}

No confirmed barriers identified in the WCRP have been rehabilitated as of 2026.

## Annual Progress Report {-}

Since March 2025 the following actions were completed:

- Informal barrier assessments were completed for 36 structures, resulting in 22 structures confirmed as barriers and 14 structures excluded as passable or non-existent, or because there was no upstream habitat. 

- Two tributary by tributary mapping workshops were held August 2025 and 88 sticky notes worth of local knowledge were collected, resulting in 3 changes to Atlantic Salmon habitat and 40 changes related to barriers and accessibility.

- The habitat, accessibility, and connectivity models were updated based on the above actions, and outputs were incorporated into this WCRP.

## Priority Barriers {-}

No priority barriers were identified through the implementation of this WCRP as of 2026. 