# Work Planning {}


## Work Plan Table {-}


```{python echo=FALSE}
#| label: tbl-S1
#| tbl-cap: "Strategy 1"
#| warning: false
#| echo: false

import numpy as np
from IPython.display import display
import pandas as pd

 
def fix_table(val):
    return str(val)

def highlighttab7(val):
    red = '#ff0000;'
    yellow = '#ffff00;'
    lgreen = '#92d050;'
    dgreen = '#03853e;'

    if val=="Medium" or val=="Need more information": color = yellow
    elif val=="Very high" or val=="Very effective" : color = lgreen
    elif val =="High" or val=="Effective": color = dgreen
    else: color = 'white'
    return 'background-color: %s' % color

```

```{python opplan, echo=FALSE}
#| label: tbl-opplan
#| tbl-cap: "SAMPLE Operational plan to support the implementation of strategies and actions to improve connectivity for target species in watershed."
#| warning: false
#| echo: false

from IPython.display import display
import pandas as pd
import numpy as np


def df_operation(val):
    return "background-color: black; color: white"


data = pd.read_csv('data/operational-plan.csv', index_col=False)

data = data.replace(np.nan, '', regex=True)

rows = pd.IndexSlice[[], :]

data = data.style.applymap(df_operation, subset=rows).hide().set_properties(**{'text-align': 'left'})
data.set_table_styles(
   [{
       'selector': 'th',
       'props': [('background-color', '#008270'),('text-align', 'left')]
   }])

```

```{r fund, echo = FALSE, results = 'asis'}
#| label: tbl-fund
#| tbl-cap: "Potential funding sources for plan implementation in <watershed>. The Canadian Wildlife Federation and the planning team can coordinate proposal submission through these sources."
#| warning: false

library("flextable")

```

## Progress Summary {-}

Initial assessments and ground truthing were completed in order to get more information on the current connectivity within the Cheticamp River watershed. As the summer of 2025 was a low water year many of the sites initially ground truthed were dry. Further assessment of priority sites will be undertaken next season to prioritize barriers and plan for remediation where necessary.


## Acknowledgments {-}

This plan is the culmination of a collaborative planning process undertaken in the Cheticamp River watershed primarily led by the Cheticamp River Salmon Association in partnership with the Canadian Wildlife Federation supported by the Atlantic Salmon Federation and the Nova Scotia Salmon Association. Without the continued dedication of these groups and individuals to the conservation and restoration of Atlantic salmon habitat this plan would not be possible. Plan development was funded by the Atlantic Salmon Federation. We were fortunate to benefit from the feedback, guidance, and wisdom of people who volunteered their time throughout this process — this publication would not have been possible without the engagement of our partners and the planning team (@tbl-opplan). 

The Canadian Wildlife Federation recognizes that the lands and waters that form the basis of this plan are the traditional unceded territory of the Mi’kmaq peoples. We are grateful for the opportunity to learn from the stewards of this land and work together to benefit Atlantic salmon and American eel.  
